### ISSUE TITLE
Feedback & Issues

### ISSUE THREAD

**Issue by Dyz89** [EtherealEmil/UsualScrap#18]
Greetings! i have been enjoying your modpack for quite a while now, sadly there is always a few mods that conflict. Yet thats okay since its still fun to use, especially when i scare my friends with the explosive tank scrap. However recently as of V56 and me retrying your pack i have to leave this post with observations

1) currently using LateGame Upgrades and both yours and this mod uses an item called "Medkit" which conflicts with each other, because if i buy one it uses LGU medkit model and i cant heal with it, if i disable it from the LGU config, yours also gets removed.

2) Trying to figure this out, but out of my mod profile that adds new items to buy, the moment i add UsualScrap the items in the shop get jumbled, for example if i buy a pro-flashlight i get a shotgun shell

These are the only issues and while i understand you are currently away from your computer, there is just but one thing i wish for you to make and thats a Config file if possible, more so to include the "Enable/Disable" items, since prices and rarity weights can be adjusted with other mods. However an true/fase config would be so helpful!

Either way, Thank you for an amazing mod and i will continue to keep an eye out for any future updates and new items you will add!

**Comment by EtherealEmil** [comment]
Thank you, I'm glad you've enjoyed it. A config for items was in the works before I left so I will get that done when I return, someone else also wanted that so I'm more than happy to add that. I will fix the medkit issue also, I'll just add a mod tag to any references of my items so that shouldn't  happen anymore. As for the jumbling of shop items I don't really know, you can't buy shotgun shells in vanilla so it's probably a mod conflict, just have to find out which mod or mods. If that is happening with only this mod or you figure out the mods conflicting please let me know, I'll try to fix that also. As you know, I'm away from my pc and currently writing from the GitHub app so I cannot work on anything regardless of how much a want to fix this stuff, It will be fixed when I return!

**Comment by EtherealEmil** [comment]
The item conflicts should be fixed now and configs have been added, enjoy! I will soon close this issue.
