### ISSUE TITLE
[Suggestion] Changes to the handlamp

### ISSUE THREAD

**Issue by Teacyn** [EtherealEmil/UsualScrap#2]
While I appreciate the idea of the handlamp a lot, I think its current state doesn't really justify being purchased over a normal flashlight. It weighs as much as a Pro Flashlight and is significantly less useful. I would personally use it a lot more if it were repurposed a bit with the intention of it being an item you don't carry around at all times, rather you "set up" the lamp somewhere and then leave it.

I feel like this would encourage using it as a "marker" of sorts and as a way to consistently illuminate larger rooms (especially useful on Mansion and some custom interiors), whereas currently it's only really helpful for a group traveling together. To that note, here's my suggestions.

- Increase weight from 5lbs to 10lbs (to discourage hauling it around all the time)
- Significantly increase light radius, but not brightness (It should be able to light up most of a room, if not the entirety not considering rooms like Mineshafts on factory)
- Greatly increase battery life. Pro Flashlight battery life isn't long enough for something of this purpose.
- Make it harder to see while carrying it (I don't actually know if this is possible, but essentially if you have it on while carrying it it should be almost blinding you.)

The idea is that the player should be bringing it in, setting it up at a junction or large room, and then leaving it there to reclaim later. I'm unsure exactly how long the battery life should be, probably not quite as long as a walkie but you shouldn't need to recharge it mid-mission unless you're using it super extensively.

Thoughts?

**Comment by EtherealEmil** [comment]
I like the ideas but I also have some hesitations I will list below.

1. Firstly, the lamp being a marker is a good idea and I could see this function working well in large rooms like the entrance rooms in the mansion or factory. However, in the factory, you are also constantly making turns, running from monsters, and searching for scrap so I'd think that having a light item that could guide you home if set up correctly but will otherwise basically blind you if used while held AND is heavier than a shovel so you'll be slower if you carry it may be more of a detriment than any help (There's also the procedurally generated aspect where some layouts will be pretty easy to remember and thus the lamp wouldn't be that helpful). So I ask, if this was implemented would you use it over a pro-flashlight OR with a pro-flashlight? And do you think it would be worth setting up the hand-lamp and traversing the halls without a hand-held light?
3. If the handlamp was to completely commit to being a marker, I can't help but feel it would fall behind one person having a spray can or one person remaining on the ship to guide everyone. what would it provide that the other two do not already?
4. Extending the battery life is a great idea generally and would give it the upper hand in at least one aspect when compared to the pro-flashlight so I'll probably change that either way.

There is also the fact that I could just make this a new item altogether and leave the handlamp in its handlampy lane or maybe there is a nice middle ground where it is a decent hand-held item but can also be effectively used as a marker. My brain is getting mangled so I thank you for the feedback and will make some changes when I get back to coding.

**Comment by Teacyn** [comment]
1. On second thought, I think I agree. It wouldn't be very useful on Factory, and that's half of the vanilla maps. I think it'd be used alongside a normal flashlight, but you'd need to be able to justify that pretty heavily since chances are you would end up losing it since you won't carry it with you all the time.
2. My reasoning here was that it'd be bright enough to be visible from several rooms away, allowing it to be easier to follow than spray paint often is. This might just be an oddity with my specific group though, we often really struggle to follow spray paint.

**Comment by EtherealEmil** [comment]
In the new update, the handlamp has received that slight light range buff and a new battery capacity that lasts 1.5x longer than a pro-flashlight.  I also noticed that with the pretty big battery buff and slight light buff it can sort of be used in the way you've described above as a rework albeit not as effective I think. If you'd like attribution for the change I can add it to the changelog if you'd like but otherwise thank you for the suggestions and I will set this to close.

**Comment by Teacyn** [comment]
No need! And thank ya for the consideration.
