### ISSUE TITLE
[Bug] Medkit does not recharge if left on ship + Explosive Tank desync

### ISSUE THREAD

**Issue by Teacyn** [EtherealEmil/UsualScrap#3]
Bug 1:

Medkits do not recharge if they are left on the ship between rounds. I have not tested if they recharge properly in general, but my group was leaving the medkit on-ship as a healing station and it suddenly stopped healing after 10 rounds or so. I assume it ran out of charge, and I couldn't get it to recharge.

Bug 2:

The explosive tank exploding does not sync between players if it explodes on a different round. Noticed this because we were messing around on a failed quota, each of us were able to blow the tank up individually. Also, the tank only deals damage to the person who hits it, though I assume this is an intentional anti-griefing thing.

Addendum edit: Tanks seem to be pretty bad with syncing in general. They usually vanish if we close and reopen lobby.

**Comment by EtherealEmil** [comment]
Because of how I have it set up, the medkit is recharged when BROUGHT to the ship so if you just pick it up, walk out of the ship, and then walk back in it will be recharged. I can figure something out so it'll stay charged when in the ship. The explosive tank needs some networking code which I neglected to do but am in the process of learning, it'll be fixed soon.

**Comment by EtherealEmil** [comment]
The medkit change has been implemented and I've tried fixing the explosive tank is this next update that i will release later today. I will close this now, thanks for the help.
