### ISSUE TITLE
Gift wrap Invisible presents 

### ISSUE THREAD

**Issue by WULFXP** [EtherealEmil/UsualScrap#5]
Playing in multiplayer with friends, I am the host my friends are saying after using the gift wrap they're seeing presents that aren't there for me. Thank you :D

**Comment by EtherealEmil** [comment]
Are they using the gift wrap or are you? And are you the only one who doesn't see it? This should hopefully be an easy fix as I already have some ideas about what's happening.

**Comment by Teacyn** [comment]
Can confirm the same here. If I unwrap a present that I gift wrapped, other players can still see the present.

**Comment by EtherealEmil** [comment]
OH ok, I didn't quite understand the issue the first time but I do now. While I'll try to fix the issue, the version I have has a bunch of code changes but I haven't released it yet, if the issue is still present with the next update I release I will then focus on fixing it.

**Comment by Teacyn** [comment]
While this bug is fixed, a new bug has arrived where it now creates three gift boxes that other players can't see. Two of them can be picked up, meaning you now get a duplicate scrap (the two tanks here). The third is completely uninteractive and is only visible to the person who used the wishlist. It also tends to spawn an extra non-interactive wishlist. The wishlist seems to just not sync properly at all.

![image](https://github.com/EtherealEmil/UsualScrap/assets/12898157/378d8adc-d72f-40d8-8962-d5a3732da2e0)

**Comment by EtherealEmil** [comment]
Alright, I'll see if I can fix it but I may just disable it and come back to it later. Getting kind of annoyed of it having issues. Sorry about that.
